### ISSUE TITLE
Level0 solution fails

### ISSUE THREAD

**Issue by victoryeo** [RealJohnnyTime/ethernaut-foundry-solutions-johnnytime#1]
$ forge script script/Level0Solution.s.sol —-broadcast
[⠘] Compiling...
[⠰] Compiling 17 files with 0.6.12
[⠒] Solc 0.6.12 finished in 4.53s
Compiler run successful
Traces:
  [288242] → new Level0Solution@0x5b73C5498c1E3b4dbA84de0F1833c4a029d90519
    └─ ← 1329 bytes of code

  [26242] Level0Solution::run() 
    ├─ [0] 0x0c49511429317D3B4E308Eab5185090c1Fe752BC::password() [staticcall]
    │   └─ ← ()
    └─ ← "EvmError: Revert"

Error: 
Script failed.

the private key has been supplied in .env

**Comment by victoryeo** [comment]
this is the correct test script
```
contract Level0Solution is Script {

    Level0 public level0 = Level0(0x0c49511429317D3B4E308Eab5185090c1Fe752BC);

    function run() external {
        Level0 level0 = new Level0("password");
        string memory password = level0.password();
        console.log("Password: ", password);
        vm.startBroadcast(vm.envUint("PRIVATE_KEY"));
        level0.authenticate(password);
        vm.stopBroadcast();
    }
}
```

**Comment by victoryeo** [comment]
Actually you use the explicit conversion from address to contract type ,  but no contract is ever deployed on that address 0x0c49511429317D3B4E308Eab5185090c1Fe752BC

**Comment by RealJohnnyTime** [comment]
Hey there! To make sure you're using the right address, deploy your own instance and replace the existing one. The current address belongs to my deployed instances, and it could be on a different chain (Goerli/Sepolia) or might have been hacked by me already. I've actually covered this in my videos, so feel free to check them out for more info! 😊
